title: Automations
path: Automations
icon: 'mdi:creation'
type: custom:vertical-stack-in-card
cards:
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - domain: automation

   