title: Automations
path: Automations
icon: 'mdi:creation'
cards:
    - type: custom:monster-card
      card:
        type: entities
        title: Automations
        show_header_toggle: false
      filter:
        include:
          - domain: automation

   