homeassistant:


group:
  System_monitor:
    name: System monitor
    view: yes
    entities:
      - sensor.ha_installed_version
      - sensor.ha_current_version
      - sensor.ha_last_restart
      - sensor.processor_use
      - sensor.memory_free
      - sensor.memory_use_percent
      - sensor.disk_free
      - sensor.disk_use
      - sensor.disk_use_percent
      - sensor.ipv4_address_wlan0
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.cpu_temperature
      - sensor.load_1m

  Internet_status:
    name: Internet status
    view: yes
    entities:
      - sensor.speedtest_ping
      - sensor.speedtest_upload
      - sensor.speedtest_download
      - sensor.external_ip   


speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload 

sensor:

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: ipv4_address
        arg: wlan0
      - type: memory_free  
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      - type: load_1m

  
  - platform: rest
    resource: http://icanhazip.com
    name: external_ip
    value_template: '{{ value }}'
    scan_interval: 60

  - platform: command_line
    name: CPU Temperature
    command: cat /sys/class/thermal/thermal_zone0/temp
    unit_of_measurement: '°C'
    value_template: '{{ value | multiply(0.001) }}'


  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: HA Current Version
    value_template: '{{ value_json.info.version }}'
    scan_interval: 86400

  - platform: file
    name: HA Installed Version
    file_path: /config/.HA_VERSION
    scan_interval: 86400


  - platform: template
    sensors:
      ha_last_restart:
        value_template: '{{ as_timestamp(states.automation.home_assistant_startup_notification.attributes.last_triggered) | timestamp_custom("%b %d %X") }}'
        friendly_name: HA Last Restart



<<<<<<< HEAD
automation:
  - alias: Notify Of New External IP
    id: '1545644322222'
    trigger:
      platform: state
      entity_id: sensor.external_ip
    action:
    - service: notify.slack
      data_template:
        message: 'Your External IP :  {{ states.sensor.external_ip.state }} '
  # - alias: Update notifications
  #   id: '918273645'
  #   trigger:
  #     platform: state
  #     entity_id: binary_sensor.updater
  #     to: on
  #   action:
  #   - service: notify.slack
  #     data_template:
  #       title: New Home Assistant Release
  #       message: Home Assistant  {{ states.updater.updater.state }}  is now available.
  - id: '1545644325295'
    alias: Home Assistant startup notification
    trigger:
    - event: start
      platform: homeassistant
    action:
    - service: notify.slack
      data_template:
        message: Home assistant restarted successfully!
        title: Hass restart notification
=======
 
>>>>>>> aa66de496979c34a4a8d0561b9a83805219edfca
