homeassistant:
  customize:
    device_tracker.google_maps_103126718451005809779:
      friendly_name: Kavita
      entity_picture: !secret kavita_picture
    device_tracker.google_maps_115135655450274737088:
      friendly_name: Hemant
      entity_picture:  !secret hemant_picture

group:
  family:
    name: Family
    entities:
      - device_tracker.google_maps_103126718451005809779
      - device_tracker.google_maps_115135655450274737088

device_tracker:
  - platform: google_maps
    username: !secret device_tracker_google_account
    scan_interval: 60


sensor:
  - platform: history_stats
    name: Time spent at Home
    entity_id: device_tracker.google_maps_115135655450274737088
    state: 'home'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
 
  - platform: history_stats
    name: Time spent away from home
    entity_id: device_tracker.google_maps_115135655450274737088
    state: 'not_home'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'



automation:
- alias: Announce Hemant's arrival
  trigger:
    platform: state
    entity_id: person.hemant
    to: 'home'
    for:
      seconds: 30
  action:
    - service: notify.slack
      data:
        message: Hemant just arrived at home.
    - service: tts.google_say
      entity_id: media_player.google_home
      data: 
        message: Hemant just arrived at home.


- alias: Announce Kavita's arrival
  trigger:
    platform: state
    entity_id: person.kavita
    to: 'home'
    for:
      seconds: 30
  action:
    - service: notify.slack
      data:
        message: Kavita just arrived at home.
    - service: tts.google_say
      entity_id: media_player.google_home
      data: 
        message: Kavita just arrived at home.        
