homeassistant:
  customize:
    device_tracker.google_maps_103126718451005809779:
      friendly_name: Kavita
      entity_picture: https://lh6.googleusercontent.com/-w2o91xokRMY/AAAAAAAAAAI/AAAAAAAAALc/CzfY60zSY1g/photo.jpg
    device_tracker.google_maps_115135655450274737088:
      friendly_name: Hemant
      entity_picture: https://lh4.googleusercontent.com/-4RPqLKZcZoM/AAAAAAAAAAI/AAAAAAAAGG0/SwTihr6JHtw/photo.jpg

group:
  family:
    name: Family
    view: yes
    entities:
      - device_tracker.google_maps_103126718451005809779
      - device_tracker.google_maps_115135655450274737088

device_tracker:
  - platform: google_maps
    username: !secret device_tracker_google_account


automation:
- alias: Announce Hemant's arrival
  trigger:
    platform: state
    entity_id: person.hemant
    to: 'home'
    for:
      seconds: 30
  action:
    - service: notify.slack
      data:
        message: Hemant just arrived at home.
    - service: tts.google_say
      data: 
        message: Hemant just arrived at home.


- alias: Announce Kavita's arrival
  trigger:
    platform: state
    entity_id: person.kavita
    to: 'home'
    for:
      seconds: 30
  action:
    - service: notify.slack
      data:
        message: Kavita just arrived at home.
    - service: tts.google_say
      data: 
        message: Kavita just arrived at home.        
