- id: '1572851158261'
  alias: Sleep data
  description: ''
  trigger:
  - at: 09:00:00
    platform: time
  condition:
  - condition: template
    value_template: '{{ state_attr("sensor.hemant_sleep", "sleep") == None }}'
  action:
  - data:
      message: Sleep data not yet synced with Google fit. Please open Mi Fit app and sync sleep data to Google Fit.
    service: notify.slack
