homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
    - type: legacy_api_password
      api_password: !secret http_password
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 560
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config

  packages: !include_dir_named packages  

http:
  server_host: 192.168.1.200
  server_port: 80

# duckdns:
#   domain: !secret duckdns_domain
#   access_token: !secret duckdns_access_token

default_config:

media_extractor:

person:

stream:

config:

map:

discovery:

system_health:

updater:

mobile_app:

logger:
  default: error

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

cast:
  media_player:
    - host: 192.168.1.101

tts:
  - platform: google_translate
    service_name: google_say

recorder: !include recorder.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
notify: !include notification.yaml
zone: !include zones.yaml

   



