homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 560
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config

default_config:
person:

config:

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
history:
  # include:
  #   domains:
  #     - sensor
  #     - switch
  #     - media_player
  #     - device_tracker

logbook:
  # include:
  #   domains:
  #     - sensor
  #     - switch
  #     - media_player
  #     - device_tracker

# lovelace:
#   mode: yaml

http:
  #base_url: !secret domain_name
  server_port: 80


#https://home-assistant.io/components/logger/
logger:
  default: error

#https://www.home-assistant.io/components/map/
map:

#https://home-assistant.io/components/sun/
sun:
discovery:

system_health:

updater:
automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
#input_select: !include input_select.yaml
light: !include lights.yaml
notify: !include notification.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
switch: !include switches.yaml
zone: !include zones.yaml
group: !include groups.yaml

  

panel_iframe:
  cctv:
    title: 'CCTV'
    url: 'http://192.168.1.115:8765'    

   
    
####################################################
#                                                  #
#                     MQTT                         #
#                                                  #
####################################################

#https://home-assistant.io/docs/mqtt/broker/#run-your-own
mqtt:
  broker: localhost
  port: 1883
  client_id: smarthome
  keepalive: 60
  protocol: 3.1
  birth_message:
    topic: "tele/smarthome/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/smarthome/LWT"
    payload: "Offline"
    qos: 1
    retain: true

# duckdns:
  # domain: !secret domain_name
  # access_token: !secret domain_access_token    

weather:
  - platform: darksky
    api_key: !secret darksky
    latitude: !secret latitude
    longitude: !secret longitude
    mode: hourly


device_tracker:
  - platform: google_maps
    username: !secret device_tracker_google_account
    password: !secret device_tracker_google_account_password
    interval_seconds: 60
    consider_home: 60

camera:
  - platform: generic
    name: CCTV
    still_image_url: http://192.168.1.115:8081/
    verify_ssl: false   

tts:
  - platform: google
    #base_url: http://192.168.1.100


speedtestdotnet:
  scan_interval:
    minutes: 30

cast:
  media_player:
    - host: 192.168.1.101

  monitored_conditions:
    - ping
    - download
    - upload

# googlehome:
#   devices:
#     - host: 192.168.1.101
#       track_alarms: true   
