version: '3.7'

services:

  # Database for HA
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./shared:/shared
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
      TZ: ${TZ}
  
  # MQTT broker
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    restart: always
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/log:/mosquitto/log
    environment:
      TZ: ${TZ}
      MOSQUITTO_USERNAME: ${MOSQUITTO_USERNAME}
      MOSQUITTO_PASSWORD: ${MOSQUITTO_PASSWORD}
  
# Home Assistant
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    restart: always
    ports:
      - "8123:8123"
    depends_on:
      - postgres
      - mosquitto
    volumes:
      - /home/hemant/home-assistant/config:/config
      - ./shared:/shared
      - ./certs:/certs:ro
      - ./data/log:/log
      - ./scripts:/scripts:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${TZ}
      HOSTIP: ${HOSTIP}
