background: center / cover no-repeat url("/www/custom_ui/background2.jpg") fixed
title: Sweet Home
views:
  - cards:
      - cards:
          - entity: sensor.processor_use
            severity:
              green: 0
              red: 85
              yellow: 45
            title: cpu usage
            type: gauge
            unit_of_measurement: '%'
          - entity: sensor.disk_use_percent
            severity:
              green: 0
              red: 85
              yellow: 65
            title: Disk usage
            type: gauge
            unit_of_measurement: '%'
          - entity: sensor.memory_use_percent
            severity:
              green: 0
              red: 85
              yellow: 50
            title: Memory usage
            type: gauge
            unit_of_measurement: '%'
          - entity: sensor.cpu_temperature
            severity:
              green: 30
              red: 85
              yellow: 55
            title: cpu temperature
            type: gauge
            unit_of_measurement: C
        type: horizontal-stack
      - cards:
          - accuracy: 30
            entity: sensor.speedtest_download
            hours_to_show: 24
            line_color: '#03a9f4'
            line_width: 8
            name: Download
            type: sensor
          - accuracy: 30
            entity: sensor.speedtest_upload
            hours_to_show: 24
            line_color: '#03a9f4'
            line_width: 8
            name: Upload
            type: sensor
        type: horizontal-stack
      - entities:
          - entity: sensor.ha_installed_version
          - entity: sensor.ha_current_version
          - entity: sensor.ha_last_restart
          - entity: sensor.processor_use
          - entity: sensor.memory_free
          - entity: sensor.memory_use_percent
          - entity: sensor.disk_free
          - entity: sensor.disk_use
          - entity: sensor.disk_use_percent
          - entity: sensor.ipv4_address_wlan0
          - entity: sensor.last_boot
          - entity: sensor.cpu_temperature
          - entity: sensor.load_1m
          - entity: sensor.load_5m
          - entity: sensor.load_15m
        type: entities
      - entities:
          - entity: sensor.speedtest_ping
          - entity: sensor.speedtest_upload
          - entity: sensor.speedtest_download
          - entity: sensor.external_ip
        show_header_toggle: false
        title: Internet speed
        type: entities
      - hold_action:
          action: none
        image: 'http://192.168.1.115:8765/picture/1/current/'
        tap_action:
          action: none
        type: picture
    icon: 'mdi:home-assistant'
    title: HA
  - cards:
      - entities:
          - sensor.hemant_birthday_days2go
          - sensor.kavita_birthday_days2go
          - sensor.pranav_birthday_days2go
          - sensor.parth_birthday_days2go
        title: Birthdays
        type: glance
      - entities:
          - entity: switch.livingroom
            icon: 'mdi:toggle-switch'
            name: Living room
          - entity: switch.kitchen
            icon: 'mdi:toggle-switch'
            name: Kitchen
          - entity: switch.masterbedroom
            icon: 'mdi:toggle-switch'
            name: Master bedroom
          - entity: switch.bedroom
            icon: 'mdi:toggle-switch'
            name: Bedroom
          - entity: switch.tv
            icon: 'mdi:toggle-switch'
            name: TV
        show_header_toggle: false
        title: Sonoff Switches
        type: entities
      - cards:
          - cards:
              - accuracy: 30
                entity: sensor.voltage
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Voltage
                type: sensor
              - accuracy: 30
                entity: sensor.current
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Current
                type: sensor
              - accuracy: 30
                entity: sensor.energy
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Energy
                type: sensor
            type: horizontal-stack
          - cards:
              - accuracy: 30
                entity: sensor.power
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Power
                type: sensor
              - accuracy: 30
                entity: sensor.power_factor
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Power factor
                type: sensor
              - accuracy: 30
                entity: sensor.total
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Total
                type: sensor
            type: horizontal-stack
        type: vertical-stack
      - entities:
          - entity: sensor.hemant_steps
          - entity: sensor.hemant_distance
          - entity: sensor.hemant_move_time
          - entity: sensor.hemant_calories
          - entity: sensor.hemant_weight
          - entity: sensor.hemant_height
          - entity: sensor.hemant_sleep
          - entity: sensor.hemant_sleep_bedtime
          - entity: sensor.hemant_sleep_deep_sleep
          - entity: sensor.hemant_sleep_light_sleep
          - entity: sensor.hemant_sleep_wake_up_time
        show_header_toggle: false
        title: Google Fit
        type: entities
      - entities:
          - entity: sensor.ha_installed_version
          - entity: sensor.ha_current_version
          - entity: sensor.ha_last_restart
          - entity: sensor.processor_use
          - entity: sensor.memory_free
          - entity: sensor.memory_use_percent
          - entity: sensor.disk_free
          - entity: sensor.disk_use
          - entity: sensor.disk_use_percent
          - entity: sensor.ipv4_address_wlan0
          - entity: sensor.last_boot
          - entity: sensor.cpu_temperature
          - entity: sensor.load_1m
          - entity: sensor.load_5m
          - entity: sensor.load_15m
        show_header_toggle: false
        title: System information
        type: entities
      - entities:
          - entity: sensor.speedtest_ping
          - entity: sensor.speedtest_upload
          - entity: sensor.speedtest_download
          - entity: sensor.external_ip
        show_header_toggle: false
        title: Internet speed
        type: entities
      - entities:
          - entity: switch.tv
          - entity: sensor.voltage
          - entity: sensor.current
          - entity: sensor.energy
          - entity: sensor.power
          - entity: sensor.power_factor
          - entity: sensor.yesterday
          - entity: sensor.total
        show_header_toggle: true
        title: TV
        type: entities
      - entities:
          - entity: sensor.mcp9808
          - entity: sensor.living_room_temperature
          - entity: sensor.living_room_humidity
          - entity: sensor.living_room_pressure
          - entity: sensor.living_room_ruuvi_battery
        show_header_toggle: false
        title: Living room sensors
        type: entities
      - entities:
          - entity: sensor.bed_room_temperature
          - entity: sensor.bed_room_humidity
          - entity: sensor.bed_room_pressure
          - entity: sensor.bed_room_ruuvi_battery
        show_header_toggle: false
        title: Bed room sensors
        type: entities
      - entities:
          - entity: sensor.sonoff_sc_temperature
          - entity: sensor.sonoff_sc_humidity
          - entity: sensor.sonoff_sc_noise
          - entity: sensor.sonoff_sc_light
          - entity: sensor.sonoff_sc_air_quality
        show_header_toggle: false
        title: Air quality sensors
        type: entities
      - entities:
          - entity: sun.sun
          - entity: sensor.sunrise_time
          - entity: sensor.sunset_time
        show_header_toggle: false
        title: Sun
        type: entities
      - entities:
          - entity: binary_sensor.workday_sensor
        show_header_toggle: false
        title: Work
        type: entities
      - entity: weather.dark_sky
        name: Weather
        type: weather-forecast
      - entities:
          - entity: sensor.mahadiscom_250410062255_billamount
          - entity: sensor.mahadiscom_250410062255_billdate
          - entity: sensor.mahadiscom_250410062255_billmonth
          - entity: sensor.mahadiscom_250410062255_consumptionunits
          - entity: sensor.mahadiscom_250410062255_duedate
          - entity: sensor.mahadiscom_250410062255_promptpaymentdate
        show_header_toggle: false
        title: Mahadiscom energy bill Bhadole
        type: entities
      - entities:
          - entity: sensor.mahadiscom_170020034907_billdate
          - entity: sensor.mahadiscom_170020034907_billamount
          - entity: sensor.mahadiscom_170020034907_billmonth
          - entity: sensor.mahadiscom_170020034907_consumptionunits
          - entity: sensor.mahadiscom_170020034907_duedate
          - entity: sensor.mahadiscom_170020034907_promptpaymentdate
        show_header_toggle: false
        title: Mahadiscom energy bill Ambegaon
        type: entities
      - entities:
          - entity: sensor.mahadiscom_170850116400_billdate
          - entity: sensor.mahadiscom_170850116400_billamount
          - entity: sensor.mahadiscom_170850116400_billmonth
          - entity: sensor.mahadiscom_170850116400_consumptionunits
          - entity: sensor.mahadiscom_170850116400_duedate
          - entity: sensor.mahadiscom_170850116400_promptpaymentdate
        show_header_toggle: false
        title: Mahadiscom energy bill Nanded city
        type: entities
      - entities:
          - entity: sensor.mngl_amount
          - entity: sensor.mngl_billdate
          - entity: sensor.mngl_billduedate
          - entity: sensor.mngl_billno
        show_header_toggle: false
        title: MNGL Bill
        type: entities
    icon: 'mdi:home'
    theme: dark-mode
    title: Rooms
  - cards:
      - cards:
          - entity: sensor.living_room_temperature
            severity:
              green: 0
              red: 35
              yellow: 25
            type: gauge
            unit_of_measurement: C
          - entity: sensor.living_room_humidity
            severity:
              green: 0
              red: 85
              yellow: 65
            type: gauge
            unit_of_measurement: '%Rh'
          - entity: sensor.living_room_pressure
            severity:
              green: 800
              red: 1000
              yellow: 950
            type: gauge
            unit_of_measurement: hPa
        type: horizontal-stack
      - entity: sensor.bed_room_temperature
        graph: line
        name: Bed room temperature
        type: sensor
      - cards:
          - entity: sensor.bed_room_temperature
            severity:
              green: 0
              red: 35
              yellow: 25
            type: gauge
            unit_of_measurement: C
          - entity: sensor.bed_room_humidity
            severity:
              green: 0
              red: 85
              yellow: 65
            type: gauge
            unit_of_measurement: '%Rh'
          - entity: sensor.bed_room_pressure
            severity:
              green: 800
              red: 1000
              yellow: 950
            type: gauge
            unit_of_measurement: hPa
        type: horizontal-stack
      - entity: sensor.living_room_temperature
        graph: line
        name: Living room temperature
        type: sensor
      - entity: sensor.living_room_humidity
        graph: line
        name: Living room humidity
        type: sensor
      - entity: sensor.bed_room_humidity
        graph: line
        name: Bed room humidity
        type: sensor
      - entity: sensor.living_room_pressure
        graph: line
        name: Living room pressure
        type: sensor
      - entity: sensor.bed_room_pressure
        graph: line
        name: Bed room pressure
        type: sensor
      - entity: sensor.living_room_ruuvi_battery
        graph: line
        name: Living room ruuvi battery
        type: sensor
      - entity: sensor.bed_room_ruuvi_battery
        graph: line
        name: Bed room ruuvi battery
        type: sensor
      - entities:
          - sensor.Living_room_temperature
        hours_to_show: 168
        name: Living ROOM
        points_per_hour: 0.25
        type: 'custom:mini-graph-card'
      - entities:
          - sensor.living_room_temperature
          - sensor.bed_room_temperature
        title: Temperatures
        type: history-graph
    title: Environment
  - cards:
      - entities:
          - entity: switch.livingroom
            icon: 'mdi:toggle-switch'
            name: Living room
          - entity: switch.kitchen
            icon: 'mdi:toggle-switch'
            name: Kitchen
          - entity: switch.masterbedroom
            icon: 'mdi:toggle-switch'
            name: Master bedroom
          - entity: switch.bedroom
            icon: 'mdi:toggle-switch'
            name: Bedroom
          - entity: switch.tv
            icon: 'mdi:toggle-switch'
            name: TV
        show_header_toggle: false
        title: Sonoff Switches
        type: entities
      - cards:
          - cards:
              - accuracy: 30
                entity: sensor.voltage
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Voltage
                type: sensor
              - accuracy: 30
                entity: sensor.current
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Current
                type: sensor
              - accuracy: 30
                entity: sensor.energy
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Energy
                type: sensor
            type: horizontal-stack
          - cards:
              - accuracy: 30
                entity: sensor.power
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Power
                type: sensor
              - accuracy: 30
                entity: sensor.power_factor
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Power factor
                type: sensor
              - accuracy: 30
                entity: sensor.total
                hours_to_show: 24
                line_color: '#03a9f4'
                line_width: 8
                name: Total
                type: sensor
            type: horizontal-stack
        type: vertical-stack
    title: Switches
  - cards:
      - entity: weather.dark_sky
        type: weather-forecast
    icon: 'mdi:weather-cloudy'
    id: weather
    title: Weather
  - badges: []
    cards:
      - entities:
          - entity: device_tracker.google_maps_103126718451005809779
          - entity: device_tracker.google_maps_115135655450274737088
        type: glance
      - entities:
          - entity: device_tracker.google_maps_103126718451005809779
          - entity: device_tracker.google_maps_115135655450274737088
        type: map
      - entities:
          - device_tracker.google_maps_115135655450274737088
          - device_tracker.google_maps_103126718451005809779
        hours_to_show: 1
        refresh_interval: 10
        type: history-graph
    icon: 'mdi:pin'
    title: Who's where?
