####################################################
#                                                  #
#                      RESOURCE                    #
#                                                  #
####################################################

resources:
  #https://github.com/thomasloven/lovelace-slider-entity-row
  - url: /www/custom_ui/slider-entity-row.js
    type: js

####################################################
#                                                  #
#                       HOME                       #
#                                                  #
####################################################

title: Sweet Home
background: center / cover no-repeat url("/www/custom_ui/background2.jpg") fixed
views:

  - title: Rooms
    icon: mdi:home
    theme: dark-mode
    cards:
      - type: glance
        title: Birthdays
        entities:
            - sensor.hemant_birthday_days2go
            - sensor.kavita_birthday_days2go
            - sensor.pranav_birthday_days2go
            - sensor.parth_birthday_days2go
      - type: entities
        title: Sonoff Switches
        show_header_toggle: false
        entities:
          - entity: switch.livingroom
            name: Living room
            icon: mdi:toggle-switch
          - entity: switch.kitchen
            name: Kitchen
            icon: mdi:toggle-switch
          - entity: switch.masterbedroom
            name: Master bedroom
            icon: mdi:toggle-switch
          - entity: switch.bedroom
            name: Bedroom
            icon: mdi:toggle-switch
          - entity: switch.tv
            name: TV
            icon: mdi:toggle-switch
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
          
              - type: sensor
                entity: sensor.voltage
                name: Voltage
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24
              - type: sensor
                entity: sensor.current
                name: Current
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24
              - type: sensor
                entity: sensor.energy
                name: Energy
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24  
          - type: horizontal-stack
            cards:             
              - type: sensor
                entity: sensor.power
                name: Power
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24
              - type: sensor
                entity: sensor.power_factor
                name: Power factor
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24
              - type: sensor
                entity: sensor.total
                name: Total
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24 



####################################################
#                                                  #
#                HOME ASSISTANT                    #
#                                                  #
####################################################

  - title: HA
    icon: mdi:home-assistant
    cards:
      - type: horizontal-stack
        cards:
          - type: gauge
            title: cpu usage
            entity: sensor.processor_use
            unit_of_measurement: '%'      
            severity:
              green: 0
              yellow: 45
              red: 85
          - type: gauge
            title: Disk usage
            entity: sensor.disk_use_percent_
            unit_of_measurement: '%'      
            severity:
              green: 0
              yellow: 65
              red: 85    
          - type: gauge
            title: Memory usage
            entity: sensor.memory_use_percent
            unit_of_measurement: '%'      
            severity:
              green: 0
              yellow: 50
              red: 85
          - type: gauge
            title: cpu temperature
            entity: sensor.cpu_temperature
            unit_of_measurement: C      
            severity:
              green: 30
              yellow: 55
              red: 85     


 
  
      - type: glance
        title: Home Assistant Info
        entities:
          - entity: sensor.ha_installed_version
            name: Installed
            icon: mdi:home-assistant
          - entity: sensor.ha_current_version
            name: Latest Release
            icon: mdi:github-circle
          - entity: sensor.ha_last_restart
            name: Last restart
            icon: mdi:home-assistant
        columns: 3
      - type: entities
        title: Batteries
        show_header_toggle: true
        entities:
          - entity: sensor.ruuvi_battery
            icon: mdi:battery-50
            name: RuuviTag Battery
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.speedtest_download
            name: Download
            line_color: '#03a9f4'
            line_width: 8
            accuracy: 30
            hours_to_show: 24
          - type: sensor
            entity: sensor.speedtest_upload
            name: Upload
            line_color: '#03a9f4'
            line_width: 8
            accuracy: 30
            hours_to_show: 24

####################################################
#                                                  #
#               Environment                #
#                                                  #
####################################################

  - title: Environment
    cards:
      - type: glance
        title: RuuviTag
        entities:
          - sensor.ruuvi_temperature
          - sensor.ruuvi_humidity
          - sensor.ruuvi_pressure
          - sensor.ruuvi_battery
          - sensor.ruuvi_rssi
      - type: glance
        title: Air quality sensors
        entities:
          - sensor.sonoff_sc_temperature
          - sensor.sonoff_sc_humidity
          - sensor.sonoff_sc_noise
          - sensor.sonoff_sc_light
          - sensor.sonoff_sc_air_quality



####################################################
#                                                  #
#                   SWITCHES                       #
#                                                  #
####################################################

  - title: Switches
    cards:
      - type: entities
        title: Sonoff Switches
        show_header_toggle: false
        entities:
          - entity: switch.livingroom
            name: Living room
            icon: mdi:toggle-switch
          - entity: switch.kitchen
            name: Kitchen
            icon: mdi:toggle-switch
          - entity: switch.masterbedroom
            name: Master bedroom
            icon: mdi:toggle-switch
          - entity: switch.bedroom
            name: Bedroom
            icon: mdi:toggle-switch
          - entity: switch.tv
            name: TV
            icon: mdi:toggle-switch
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
          
              - type: sensor
                entity: sensor.voltage
                name: Voltage
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24
              - type: sensor
                entity: sensor.current
                name: Current
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24
              - type: sensor
                entity: sensor.energy
                name: Energy
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24  
          - type: horizontal-stack
            cards:             
              - type: sensor
                entity: sensor.power
                name: Power
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24
              - type: sensor
                entity: sensor.power_factor
                name: Power factor
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24
              - type: sensor
                entity: sensor.total
                name: Total
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24 

####################################################
#                                                  #
#                     WEATHER                      #
#                                                  #
####################################################

  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
    cards:
      - type: weather-forecast
        entity: weather.dark_sky


####################################################
#                                                  #
#          END OF CONFIGURATION FILE               #
#                                                  #
####################################################
