homeassistant:

group:
  Weather:
    name: Weather
    view: yes
    entities:
      - weather.darksky

weather:
  - platform: darksky
    api_key: !secret darksky
    latitude: !secret latitude
    longitude: !secret longitude
<<<<<<< HEAD
    mode: hourly


sensor:
  - platform: waqi
    token: !secret aqicn_token
    locations:
      - Katraj, Pune, Pune, India  
=======
    mode: hourly
>>>>>>> aa66de496979c34a4a8d0561b9a83805219edfca
