homeassistant:
  customize:
    sensor.hemant_sleep_bedtime:
      friendly_name: Bedtime
      icon: mdi:hotel
    sensor.hemant_calories:
      friendly_name: Calories
    sensor.hemant_sleep_deep_sleep:
      friendly_name: Deep sleep time
      icon: mdi:sleep
    sensor.hemant_sleep_light_sleep:
      friendly_name: Light sleep
    sensor.hemant_distance:
      friendly_name: Distance
    sensor.hemant_move_time:
      friendly_name: Move time
    sensor.hemant_weight:
      friendly_name: Weight
    sensor.hemant_height:
      friendly_name: Height
    sensor.hemant_sleep:
      friendly_name: Sleep
    sensor.hemant_sleep_wake_up_time:
      friendly_name: Wakeup time
      icon:  mdi:white-balance-sunny
    sensor.hemant_steps:
      friendly_name: Steps  

    sensor.kavita_sleep_bedtime:
      friendly_name: Bedtime
      icon: mdi:hotel
    sensor.kavita_calories:
      friendly_name: Calories
    sensor.kavita_sleep_deep_sleep:
      friendly_name: Deep sleep time
      icon: mdi:sleep
    sensor.kavita_sleep_light_sleep:
      friendly_name: Light sleep
      icon: mdi:sleep-off
    sensor.kavita_distance:
      friendly_name: Distance
    sensor.kavita_move_time:
      friendly_name: Move time
    sensor.kavita_weight:
      friendly_name: Weight
    sensor.kavita_height:
      friendly_name: Height
    sensor.kavita_sleep:
      friendly_name: Sleep
    sensor.kavita_sleep_wake_up_time:
      friendly_name: Wakeup time
      icon: mdi:white-balance-sunny
    sensor.kavita_steps:
      friendly_name: Steps    
    sensor.hemant_heartrate:
      friendly_name: Heart rate     

sensor:  
  - platform: google_fit_hass
    name: hemant
    client_id: !secret google_client_id
    client_secret: !secret google_client_secret
    scan_interval: 30

  - platform: google_fit_hass
    name: kavita
    client_id: !secret kavita_google_client_id
    client_secret: !secret kavita_google_client_secret
    scan_interval: 30


  - platform: template
    sensors:
      hemant_sleep_bedtime:
        value_template: >-
            {%- if states.sensor.hemant_sleep.attributes.bed_time %}
                {{ states.sensor.hemant_sleep.attributes.bed_time }}
            {% else %}
                {{ states.sensor.hemant_sleep.attributes.bed_time }}
            {%- endif %}


  - platform: template
    sensors:
      hemant_sleep_wake_up_time:
        value_template: >-
            {%- if states.sensor.hemant_sleep.attributes.wake_up_time %}
                {{ states.sensor.hemant_sleep.attributes.wake_up_time }}
            {% else %}
                {{ states.sensor.hemant_sleep.attributes.wake_up_time }}
            {%- endif %}            


  - platform: template
    sensors:
      kavita_sleep_bedtime:
        value_template: >-
            {%- if states.sensor.kavita_sleep.attributes.bed_time %}
                {{ states.sensor.kavita_sleep.attributes.bed_time }}
            {% else %}
                {{ states.sensor.kavita_sleep.attributes.bed_time }}
            {%- endif %}


  - platform: template
    sensors:
      kavita_sleep_wake_up_time:
        value_template: >-
            {%- if states.sensor.kavita_sleep.attributes.wake_up_time %}
                {{ states.sensor.kavita_sleep.attributes.wake_up_time }}
            {% else %}
                {{ states.sensor.kavita_sleep.attributes.wake_up_time }}
            {%- endif %}           

  # - platform: template
  #   sensors:
  #     hemant_sleep_deep_sleep:
  #       value_template: >-
  #           {%- if states.sensor.hemant_sleep.attributes.deep_sleep %}
  #               {{ states.sensor.hemant_sleep.attributes.deep_sleep }}
  #           {% else %}
  #               {{ states.sensor.hemant_sleep.attributes.deep_sleep }}
  #           {%- endif %}                       

  # - platform: template
  #   sensors:
  #     hemant_sleep_light_sleep:
  #       value_template: >-
  #           {%- if states.sensor.hemant_sleep.attributes.light_sleep %}
  #               {{ states.sensor.hemant_sleep.attributes.light_sleep }}
  #           {% else %}
  #               {{ states.sensor.hemant_sleep.attributes.light_sleep }}
  #           {%- endif %}                   


# automation:

# - alias: Notify sleep data
#   trigger:
#     platform: state
#     entity_id: sensor.hemant_sleep
#   action:
#   - service: notify.slack
#     data_template:
#       message: 'Slept :  {{ states.sensor.hemant_sleep.state }} '

automation:
  - alias: Motivate to walk morning
    trigger:
      platform: time
      at: '10:00:00'
    condition:
      condition: numeric_state
      entity_id: sensor.hemant_steps
      below: 5000 
    action:
      service: notify.slack
      data_template:
        message: You have only walked {{ states.sensor.hemant_steps.state }} steps today. You should start walking now to achive your steps goal.

  - alias: Motivate to walk afternoon
    trigger:
      platform: time
      at: '13:00:00'
    condition:
      condition: numeric_state
      entity_id: sensor.hemant_steps
      below: 7500 
    action:
      service: notify.slack
      data_template:
        message: You have only walked {{ states.sensor.hemant_steps.state }} steps today. You should start walking now to achive your steps goal.

  - alias: Motivate to walk during evening
    trigger:
      platform: time
      at: '16:00:00'
    condition:
      condition: numeric_state
      entity_id: sensor.hemant_steps
      below: 10000 
    action:
      service: notify.slack
      data_template:
        message: Hey! You have only walked {{ states.sensor.hemant_steps.state }} steps today. You should start walking now to achive your steps goal. Only few hours left!!!       