homeassistant:
  customize:
    sensor.mahadiscom_170020034907_billmonth:
      friendly_name: Bill month
      icon: mdi:calendar
    sensor.mahadiscom_170020034907_billamount:
      friendly_name: Bill amount
      icon: mdi:cash
    sensor.mahadiscom_170020034907_consumptionUnits:
      friendly_name: ConsumptionUnits
      icon: mdi:flash
    sensor.mahadiscom_170020034907_duedate:
      friendly_name: Due date
      icon: mdi:calendar            
    sensor.mahadiscom_170020034907_promptPaymentDate:
      friendly_name: Prompt payment date
      icon: mdi:calendar    
    sensor.mahadiscom_170020034907_billDate:
      friendly_name: Bill date
      icon: mdi:calendar         

    sensor.mahadiscom_250410062255_billmonth:
      friendly_name: Bill month
      icon: mdi:calendar
    sensor.mahadiscom_250410062255_billamount:
      friendly_name: Bill amount
      icon: mdi:cash
    sensor.mahadiscom_250410062255_consumptionUnits:
      friendly_name: ConsumptionUnits
      icon: mdi:flash
    sensor.mahadiscom_250410062255_duedate:
      friendly_name: Due date
      icon: mdi:calendar            
    sensor.mahadiscom_250410062255_promptPaymentDate:
      friendly_name: Prompt payment date
      icon: mdi:calendar    
    sensor.mahadiscom_250410062255_billDate:
      friendly_name: Bill date
      icon: mdi:calendar   


    sensor.mahadiscom_170850116400_billmonth:
      friendly_name: Bill month
      icon: mdi:calendar
    sensor.mahadiscom_170850116400_billamount:
      friendly_name: Bill amount
      icon: mdi:cash
    sensor.mahadiscom_170850116400_consumptionUnits:
      friendly_name: ConsumptionUnits
      icon: mdi:flash
    sensor.mahadiscom_170850116400_duedate:
      friendly_name: Due date
      icon: mdi:calendar            
    sensor.mahadiscom_170850116400_promptPaymentDate:
      friendly_name: Prompt payment date
      icon: mdi:calendar    
    sensor.mahadiscom_170850116400_billDate:
      friendly_name: Bill date
      icon: mdi:calendar   

automation:
  - alias: Electricity bill generated for Ambegaon
    id: '94123674892123'
    trigger:
      platform: state
      entity_id: sensor.mahadiscom_170020034907_billmonth
    condition:
      condition: template
      value_template: "{{ states.sensor.mahadiscom_170020034907_billmonth.state != 'unknown' }}"
    action:
    - service: notify.slack
      data:
        title: Electricity bill generated for Ambegaon home
        message: 'Electricity bill generated for Ambegaon - Bill month :  {{  states("sensor.mahadiscom_170020034907_billmonth") }}
                  Bill date:  {{  states("sensor.mahadiscom_170020034907_billdate")}} 
                  Consumption :  {{ states("sensor.mahadiscom_170020034907_consumptionunits")}} 
                  Bill amount:  {{  states("sensor.mahadiscom_170020034907_billamount") }}
                  Due date:  {{  states("sensor.mahadiscom_170020034907_duedate") }}
                  Due date:  {{  states("sensor.mahadiscom_170020034907_promptpaymentdate") }}'

  - alias: Electricity bill generated for Bhadole
    id: '21321394123674892123123213'
    trigger:
      platform: state
      entity_id: sensor.mahadiscom_250410062255_billmonth
    condition:
      condition: template
      value_template: "{{ states.sensor.mahadiscom_250410062255_billmonth.state != 'unknown' }}"
    action:
    - service: notify.slack
      data:
        title: Electricity bill generated for Bhadole home
        message: 'Electricity bill generated for Bhadole home - Bill month :  {{  states("sensor.mahadiscom_250410062255_billmonth") }}
                  Bill date:  {{  states("sensor.mahadiscom_250410062255_billdate")}} 
                  Consumption :  {{ states("sensor.mahadiscom_250410062255_consumptionunits")}} 
                  Bill amount:  {{  states("sensor.mahadiscom_250410062255_billamount") }}
                  Due date:  {{  states("sensor.mahadiscom_250410062255_duedate") }}
                  Due date:  {{  states("sensor.mahadiscom_250410062255_promptpaymentdate") }}'


sensor:
  - platform: mahadiscom
    ConsumerNo: 170020034907 # Ambegaon
    BuNumber: 4637
    consumerType: 2
    scan_interval: 86400


  - platform: mahadiscom
    ConsumerNo: 250410062255 # Bhadole
    BuNumber: 1198
    consumerType: 2
    scan_interval: 86400


  - platform: mahadiscom
    ConsumerNo: 170850116400 #Nanded_City
    BuNumber: 4860
    consumerType: 2
    scan_interval: 86400




