homeassistant:
  customize:
    sensor.mahadiscom_170020034907_billmonth:
      friendly_name: Bill month
      icon: mdi:calendar
    sensor.mahadiscom_170020034907_billamount:
      friendly_name: Bill amount
      icon: mdi:cash
    sensor.mahadiscom_170020034907_consumptionUnits:
      friendly_name: ConsumptionUnits
      icon: mdi:flash
    sensor.mahadiscom_170020034907_duedate:
      friendly_name: Due date
      icon: mdi:calendar            
    sensor.mahadiscom_170020034907_promptPaymentDate:
      friendly_name: Prompt payment date
      icon: mdi:calendar    
    sensor.mahadiscom_170020034907_billDate:
      friendly_name: Bill date
      icon: mdi:calendar         

    sensor.mahadiscom_250410062255_billmonth:
      friendly_name: Bill month
      icon: mdi:calendar
    sensor.mahadiscom_250410062255_billamount:
      friendly_name: Bill amount
      icon: mdi:cash
    sensor.mahadiscom_250410062255_consumptionUnits:
      friendly_name: ConsumptionUnits
      icon: mdi:flash
    sensor.mahadiscom_250410062255_duedate:
      friendly_name: Due date
      icon: mdi:calendar            
    sensor.mahadiscom_250410062255_promptPaymentDate:
      friendly_name: Prompt payment date
      icon: mdi:calendar    
    sensor.mahadiscom_250410062255_billDate:
      friendly_name: Bill date
      icon: mdi:calendar   


    sensor.mahadiscom_170850116400_billmonth:
      friendly_name: Bill month
      icon: mdi:calendar
    sensor.mahadiscom_170850116400_billamount:
      friendly_name: Bill amount
      icon: mdi:cash
    sensor.mahadiscom_170850116400_consumptionUnits:
      friendly_name: ConsumptionUnits
      icon: mdi:flash
    sensor.mahadiscom_170850116400_duedate:
      friendly_name: Due date
      icon: mdi:calendar            
    sensor.mahadiscom_170850116400_promptPaymentDate:
      friendly_name: Prompt payment date
      icon: mdi:calendar    
    sensor.mahadiscom_170850116400_billDate:
      friendly_name: Bill date
      icon: mdi:calendar   

sensor:

  - platform: mahadiscom
    ConsumerNo: 170020034907 # Ambegaon
    BuNumber: 4637
    consumerType: 2
    scan_interval: 86400


  - platform: mahadiscom
    ConsumerNo: 250410062255 # Bhadole
    BuNumber: 1198
    consumerType: 2
    scan_interval: 86400


  - platform: mahadiscom
    ConsumerNo: 170850116400 #Nanded_City
    BuNumber: 4860
    consumerType: 2
    scan_interval: 86400




