homeassistant:

group:
  Switches:
    name: Switches
    view: yes
    entities:
      - switch.tv
      - switch.livingRoom    
      - switch.kitchen
      - switch.bedroom
      - switch.MasterBedRoom
      - switch.washroom


switch:
  - platform: mqtt
    name: "LivingRoom"
    state_topic: "stat/sonoff-living-room/POWER"
    command_topic: "cmnd/sonoff-living-room/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
    optimistic: false
    
 
  - platform: mqtt
    name: "Kitchen"
    state_topic: "stat/sonoff-kitchen/POWER"
    command_topic: "cmnd/sonoff-kitchen/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
    optimistic: false

  - platform: mqtt
    name: "MasterBedRoom"
    state_topic: "stat/sonoff-master-bedroom/POWER"
    command_topic: "cmnd/sonoff-master-bedroom/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
    optimistic: false
  

  - platform: mqtt
    name: "washroom"
    state_topic: "stat/washroom/POWER"
    command_topic: "cmnd/washroom/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
    optimistic: false
