homeassistant:
  customize:
    sensor.Sonoff_sc_Temperature:
      friendly_name: Temperature
    sensor.Sonoff_sc_Humidity:
      friendly_name: Humidity
      icon: mdi:water-percent
    sensor.Sonoff_sc_Noise:
      friendly_name: Noise
      icon: mdi:volume-high
    sensor.Sonoff_sc_Light:
      friendly_name: Light
      icon: mdi:lightbulb
    sensor.Sonoff_sc_Air_quality:
      friendly_name: Air Quality
      icon: mdi:air-filter                  

group:
  Air_quality:
    name: Air quality sensors
    entities:
      - sensor.Sonoff_sc_Temperature
      - sensor.Sonoff_sc_Humidity
      - sensor.Sonoff_sc_Noise
      - sensor.Sonoff_sc_Light
      - sensor.Sonoff_sc_Air_quality

sensor:
  - platform: mqtt
    name: "Sonoff_sc_Temperature"
    state_topic: "tele/sonoff-sc/SENSOR"
    value_template: "{{ value_json.SonoffSC.Temperature }}"
    unit_of_measurement: "°C"
    
  - platform: mqtt
    name: "Sonoff_sc_Humidity"
    state_topic: "tele/sonoff-sc/SENSOR"
    value_template: "{{ value_json.SonoffSC.Humidity }}"
    unit_of_measurement: "%Rh"

  - platform: mqtt
    name: "Sonoff_sc_Noise"
    state_topic: "tele/sonoff-sc/SENSOR"
    value_template: "{{ value_json.SonoffSC.Noise }}"
    unit_of_measurement: "%"
    
  - platform: mqtt
    name: "Sonoff_sc_Light"
    state_topic: "tele/sonoff-sc/SENSOR"
    value_template: "{{ value_json.SonoffSC.Light }}"
    unit_of_measurement: "%"
    
  - platform: mqtt
    name: "Sonoff_sc_Air_quality"
    state_topic: "tele/sonoff-sc/SENSOR"
    value_template: "{{ value_json.SonoffSC.AirQuality }}"
    unit_of_measurement: "%"

