- alias: Doorbell notification
  id: '10293847561209'
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell
    from: 'off'
    to: 'on'
  action:
  # - service: homeassistant.turn_on
  #   entity_id: switch.Buzzer
  - service: notify.slack
    data_template: 
      message: 'Knock Knock, Someone is at door. Please open the door.'    
  - service: tts.google_say
    data_template: 
      message: 'Knock Knock, Someone is at door. Please open the door.'    


# - alias: Turn off Buzzer after 3 seconds
#   trigger:
#     platform: state
#     entity_id: binary_sensor.doorbell
#     to: 'off'
#     for:
#       seconds: 2
#   action:
#     service: homeassistant.turn_off
#     entity_id: switch.Buzzer


