- id: '12345612'
  alias: Power Problem Notification
  trigger:
  - platform: numeric_state
    entity_id: sensor.rpi_power_status
    above: 0
    for:
      minutes: 1
  condition:
  action:
    service: persistent_notification.create
    data:
      message: "Charger reported {{ states.sensor.rpi_power_status.state }}"
      title: "RPI Power Issue"        
        
- alias: TV time
  id: '100100'
  trigger:
    platform: state
    entity_id: switch.tv
    from: 'off'
    to: 'on'
    for:
      hours: 1
  action:
  - service: notify.slack
    data_template:
      message: 'Living room TV is on for 1 hour: {{states.media_player.google_chromecast.attributes.app_name,
        states.media_player.google_chromecast.attributes.media_title}}'

- alias: Notify Of New External IP
  id: '100001'
  trigger:
    platform: state
    entity_id: sensor.external_ip
  action:
  - service: notify.slack
    data_template:
      message: 'Your External IP :  {{ states.sensor.external_ip.state }} '

      
- alias: startup notification
  id: '100002'
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: notify.slack
    data_template:
      message: Home assistant restarted successfully!
      title: Hass restart notification 

- alias: Birthday Countdown 30 Days
  id: '100004'
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - sensor.hemant_birthday_days2go
    - sensor.kavita_birthday_days2go
    - sensor.pranav_birthday_days2go
    - sensor.parth_birthday_days2go
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state | int > 0 and trigger.to_state.state
      | int < 30 }}'
  action:
  - service: notify.slack
    data_template:
      message: '{{ trigger.entity_id.split(''.'')[1].split(''_'')[0] | title }}''s
        Birthday is only {{ trigger.to_state.state }} days to go!'
      
# - alias: Today is the Birthday
  # id: '100005'
  # hide_entity: true
  # trigger:
    # platform: state
    # entity_id:
    # - sensor.hemant_birthday_days2go
    # - sensor.kavita_birthday_days2go
    # - sensor.pranav_birthday_days2go
    # - sensor.parth_birthday_days2go
  # condition:
  # - condition: template
    # value_template: '{{ trigger.to_state.state | int == 0 }}'
  # action:
  # - service: notify.slack
    # data_template:
      # value1: Hurray! Today is {{ trigger.entity_id.split('.')[1].split('_')[0] |
        # title }}'s Birthday!
      # value2: ''
- alias: Today is the Birthday
  id: '100005'
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - sensor.hemant_birthday_days2go
    - sensor.kavita_birthday_days2go
    - sensor.pranav_birthday_days2go
    - sensor.parth_birthday_days2go
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state | int == 0 }}'
  action:
  - service: notify.slack
    data_template:
      message: 'Hurray! Today is {{ trigger.entity_id.split(''.'')[1].split(''_'')[0] |
        title }}''s Birthday!'
    
      
- alias: Update Current Date In MQTT
  id: '100007'
  hide_entity: true
  trigger:
    platform: time
    hours: /01
    minutes: 0
    seconds: 0
  action:
  - service: mqtt.publish
    data_template:
      topic: /home/today
      retain: true
      payload: '{{ as_timestamp(now() ) | timestamp_custom("%m-%d-%Y", true) }}'
- alias: Update Current Date On Startup
  id: '100008'
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  action:
  - delay:
      minutes: 1
  - service: mqtt.publish
    data_template:
      topic: /home/today
      retain: true
      payload: '{{ as_timestamp(now() ) | timestamp_custom("%m-%d-%Y", true) }}'